language: python

python:
  - 3.9

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite,polls manage.py 

after_success:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "lcHQz15Y5nfDQ1zmEtI0TvOiwnGwr9wMiYB10QITrx/YGaw2OGw7XVDMPHxohXtV7Iq5nK3l/vCQ9cLgmCqgjtR+fzAYefrVSl8l4SgRghpAlb1f6u+hq0fHdToUlhTO9JUTWGkVvMxh8tGVreQOL9ObvLViVlJXPnJzNU7YMmrRlnNXjS5wXCcQ0SqzhH6cr0R2ZIo2hww9sM1AgMoF1U62l+dZuBVfr56SjR5UiycgYx7nzy7jtWJ2p86Y4gKz/yTL3f/fW2W/muAkm50pot2tB+RJh+PUyC1T9XzHpbfTdQlr8u47WnWWoKr0XIMJTKvy07oicWwDdi/PFrItyqBzxc7VyBfY4RIX+keW4/quMaFrbKp4i6CtLS3MHgCVP8Pt5n25msFzwWJZ+wOwnFiEoUmw4pF6YQ9HOoL45l4xrkAiZJOTu464brSFfGf5ZWcTG/y4HJQ8G3WdMRJ2PfoMlSeyY0G4XsOsN3e88fE0Kqclnyua75a/MfmFKAbrFgQEOQROTOOvvrISjqnCrVan1gsQ67ExBaepzyI8Q7InlMniKbLqdCC4pjnWn0A/rwtZXhiFagzZFTf+9rDViM1UX2K+MB+Opbj6q2Y7bOhrwFpO2ttAVoppp81gpVjltJdFb5NB+K5FMwFVeMNtnazsUw/pqjhW+RZ7D/3Ubus="
  secret_access_key:
    secure: "nf2jpmneT6OoKT619cQqJvPqqB9AF7JTWtkvFkcFyEO3XKjBxstvsno6CNGPFaP8WyZIJhDBBHy/FfhbckI83nV1RbzvAuEGQ3LTB8mKijb4KThZzypVVwQEc2fHxAgy6ih+YFQD7M2ycTkrX0CSmdMwRghug3TA3l0MeUaamL2TNCz5lieKH74T6cQjiSK8SEFCPR59z0CMe5VfXmXN5VzksZaKw8TL8fgJHXBeNEi5yoydF/WajPHl+iJO5Xv38cEsAHAytx66mm3t/fx/zNqCDqKjAa2YIcOF/qy+ErXI4qfuBoxOcZiL5zNj9ELK3I5a0J1SnyqHBliF71mpuuc5E80/OEAOiXgVa/fGWBTJjSBP/LFJJSj1wg2auYLuzy0JiBGIJcL+uIniJv8658t9//hXSye7MhR0GvZ4yhzWN7w9R5cxXT80jrUkicucxsYLODV3fu9YZlwECRToig+sCz/5P6BjVXP9zKi6lIYrSQtIOu6K2ZKasJlklPUPCNBxxXoZmoU8jSJ0BaqqQPLTmWfNJpJTcb86ZmSNgxqZiAHmKZecDVM8hCjTVV2dTMXdZ2NdXK3BuE0gpR3GTLGcURNvCNckul4A7xVsrOf/0wMSwAPcplrCpZHWUGH7CjLXBRPhpEby4bNvxEYOmDrQt9soDwCcsSyBBbMhbyU="
  region: "us-west-2"
  app: "mysite"
  env: "django-env"
  on:
    repo: maludee/swe1-app
    branch:    
      only:     
        - main 
  # bucket_name: "the-target-S3-bucket"
